# Generated by Django 5.2.9 on 2026-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_parent_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã tham chiếu'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch SePay'),
        ),
    ]
