# Generated by Django 5.2.9 on 2026-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_wishlist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Hình ảnh biến thể'),
        ),
    ]
