# Generated by Django 5.2.9 on 2026-03-11 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (đ)')], max_length=10, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá trị giảm')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='Áp dụng cho loại phần trăm', max_digits=10, null=True, verbose_name='Giảm tối đa')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá trị đơn tối thiểu')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Giới hạn sử dụng')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('expires_at', models.DateTimeField(verbose_name='Ngày hết hạn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giảm giá'),
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='', max_length=200, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr_code', 'QR Code'), ('cod', 'COD')], default='qr_code', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon', verbose_name='Mã giảm giá'),
        ),
    ]
