# Generated by Django 5.2.9 on 2026-03-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coupon_order_address_order_discount_order_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
